APP_VERSION_LIST = ["1.1", "0.1"]

DEVICE_TYPE_LIST = ["MOBILE", "TAB", "DESKTOP"]

DEVICE_BRAND_LIST = [
    "DELL", "HP", "LENOVO", "ASUS", "ACER", "APPLE", "MICROSOFT", "SAMSUNG", "MSI", "RAZER", "APPLE",
    "SAMSUNG", "HUAWEI", "XIAOMI", "OPPO", "VIVO", "ONEPLUS", "GOOGLE", "MOTOROLA", "SONY"
]

OS_TYPES_LIST = ["ANDROID", "IOS", "WEB"]
OS_VERSION_LIST = [
    "1.0.1", "2.0.1", "1.0.3", "2.0.1", "2.0.6", "3.0.0", "3.6.1", "0.11.1", "0.8.6", "0.10.12", "0.4.5", "0.4.1",
    "1.0.11", "2.0.8"
]

FEATURE_LIST = [
    "CALENDAR", "NEWS", "REMIT", "GIFT", "HAMROPAY", "JYOTISH", "DOCTOR", "RADIO", "BANKRATES", "RECIPE",
    "VIDEO", "PODCAST", "RASHIFAL", "KUNDALI", "E-CARDS", "FOREX", "GOLD/SILVER", "BLOG/SHAHITYA", "TALI-GALI",
    "QUIZ", "NOTES", "E-LEARNING", "DATECONVERTER", "NEPALIDICTIONARY", "HAMROGAMES", "TARKARIBAZAR",
    "TITHI/MITHI", "RECHARGE"
]

EVENT_NAME_LIST = ["CLICK", "VIEW", "SCROLL", "LISTEN"]

SOURCE_LIST = ["STANDALONE", "WIDGET", "NOTIFICATION"]